### ISSUE TITLE
Failed to train the model with PyPIBugs Dataset

### ISSUE THREAD

**Issue by codingClaire** [microsoft/neurips21-self-supervised-bug-detection-and-repair#3]
Hi! I tried to extract the PyPIBugs Dataset and train the model in Supervised Learning mode using the instructions in README.md. I modified the buglab/data/diffmining/extract.py file to just extract part of the repositories from the jsonl file. I was able to split the small dataset into three datasets (train, test, and validation), but when I ran the following command,

`python -m buglab.models.train seq-great /data/splitDir-train/output.msgpack.l.gz /data/splitDir-valid/output.msgpack.l.gz /data/models/model1.pkl.gz
`
the result was as followed:

```
2022-03-09 12:29:18,743 [ptgnn.baseneuralmodel.trainer       @ MainThread  ] [INFO ]  Saving model with finalized metadata.
2022-03-09 12:29:19,691 [ptgnn.baseneuralmodel.trainer       @ MainThread  ] [INFO ]  Model has 5959939 trainable parameters.
2022-03-09 12:29:19,692 [ptgnn.baseneuralmodel.trainer       @ MainThread  ] [INFO ]  Using `cpu` for training.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/buglab/models/train.py", line 144, in <module>
    run_and_debug(lambda: run(args), args.get("--debug", False))
  File "/usr/local/lib/python3.8/dist-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "/src/buglab/models/train.py", line 144, in <lambda>
    run_and_debug(lambda: run(args), args.get("--debug", False))
  File "/src/buglab/models/train.py", line 127, in run
    trainer.train(
  File "/usr/local/lib/python3.8/dist-packages/ptgnn/baseneuralmodel/trainer.py", line 409, in train
    target_metric, improved, _ = self._run_validation(
  File "/usr/local/lib/python3.8/dist-packages/ptgnn/baseneuralmodel/trainer.py", line 306, in _run_validation
    assert num_samples > 0, "No validation data was found."
AssertionError: No validation data was found.
```

I get the same result when I changed the validation dataset path into the path of the other two datasets(for debugging). So I think it was not the problem of the validation dataset?

**Comment by mallamanis** [comment]
Hi @codingClaire,

The PyPIBugs dataset is quite small and is meant only as a test set. Consider generating a bigger random bugs dataset.

The error message here says that the validation set you provided is empty.
